export function normalizeMathMarkdown(input: string): string {
  return (
    input
      // Fix quadruple dollar signs (often generated by AI) to double dollar signs
      .replace(/\${4}/g, "$$")
      // Convert legacy [/math]...[/math] blocks to $$...$$
      .replace(/\[\/math\]([\s\S]*?)\[\/math\]/g, (_, content) => `$$${content.trim()}$$`)
      // Convert legacy [/inline]...[/inline] to $$...$$ (Streamdown inline math)
      .replace(/\[\/inline\]([\s\S]*?)\[\/inline\]/g, (_, content) => `$$${content.trim()}$$`)
      // Convert \( ... \) to $$...$$ (inline math)
      .replace(/\\{1,2}\(([\s\S]*?)\\{1,2}\)/g, (_, content) => `$$${content.trim()}$$`)
      // Convert \[ ... \] to $$...$$ (block math)
      .replace(/\\{1,2}\[([\s\S]*?)\\{1,2}\]/g, (_, content) => `$$\n${content.trim()}\n$$`)
      // Convert single $...$ to $$...$$ (inline math), but avoid currency like $10 or $5.50
      // Exclude escaped dollar signs (prefixed with \)
      .replace(
        /(?<!\\)(?<!\$)\$(?!\$)([^$\n]+?)(?<!\\)(?<!\$)\$(?!\$)/g,
        (match, content) => {
          // Matches numbers like 10, 1,000, 10.50, 1,000.50
          if (/^\d{1,3}(?:,\d{3})*(?:\.\d{1,2})?$/.test(content.trim())) {
            return match; // Keep currency as-is
          }
          return `$$${content.trim()}$$`;
        }
      )
  );
}
